/**
 * ReportExporter.jsx
 *
 * Renders a slim toolbar row that lets the user copy a Markdown report
 * to clipboard or download a PDF. All generation is pure client-side —
 * no API calls, no server round-trips.
 *
 * Props:
 *   scenario      string   — policy description
 *   nAgents       number
 *   nSteps        number
 *   meanByStep    object   — { unemployment_rate, avg_welfare,
 *                             infrastructure_score, env_score }
 *   consequence   object   — { overall, risks: [{dimension, severity,
 *                             finding, recommendation}] }
 *   scenarioLabel string?  — optional label, e.g. "Scenario A report"
 *
 * Renders null until BOTH meanByStep AND consequence are non-null.
 */
import React, { useState } from 'react';
import jsPDF from 'jspdf';

// ── Dimension order kept consistent across all outputs ─────────────────────
const DIM_ORDER = ['Employment', 'Welfare', 'Infrastructure', 'Environment'];

// Severity palette (matches ConsequencePanel)
const SEV_COLORS = {
  high:   { bg: '#FCEBEB', text: '#A32D2D', border: '#E24B4A' },
  medium: { bg: '#FAEEDA', text: '#633806', border: '#BA7517' },
  low:    { bg: '#E1F5EE', text: '#085041', border: '#1D9E75' },
};

// ── Pure helpers ────────────────────────────────────────────────────────────

/**
 * Extract start and final values from a meanByStep series.
 * Returns { empStart, empFinal, welStart, welFinal,
 *           infStart, infFinal, envStart, envFinal }
 */
function extractMetrics(meanByStep) {
  const unemp = meanByStep?.unemployment_rate || [];
  const welf  = meanByStep?.avg_welfare       || [];
  const infra = meanByStep?.infrastructure_score || [];
  const env   = meanByStep?.env_score         || [];

  const first = (arr) => arr.length ? arr[0]  : 0;
  const last  = (arr) => arr.length ? arr[arr.length - 1] : 0;

  return {
    empStart:  (1 - first(unemp)) * 100,
    empFinal:  (1 - last(unemp))  * 100,
    welStart:  first(welf),
    welFinal:  last(welf),
    infStart:  first(infra),
    infFinal:  last(infra),
    envStart:  first(env),
    envFinal:  last(env),
  };
}

/**
 * buildMarkdown — pure function: props → markdown string.
 * No side-effects, no fetch, no DOM access.
 */
export function buildMarkdown({ scenario, nAgents, nSteps, meanByStep, consequence, scenarioLabel }) {
  const date = new Date().toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
  const {
    empStart, empFinal, welStart, welFinal,
    infStart, infFinal, envStart, envFinal,
  } = extractMetrics(meanByStep);

  const fmtDelta = (v, decimals = 1, suffix = '') => {
    const sign = v >= 0 ? '+' : '';
    return `${sign}${v.toFixed(decimals)}${suffix}`;
  };

  const title = scenarioLabel ? `CivicTwin Policy Impact Report — ${scenarioLabel}` : 'CivicTwin Policy Impact Report';

  // Sort risks into canonical order
  const risks = DIM_ORDER.map(
    dim => consequence.risks?.find(r => r.dimension === dim)
  ).filter(Boolean);

  const riskBlocks = risks.map(r =>
    `### ${r.dimension} — ${r.severity} risk\n${r.finding}\n\n**Recommendation:** ${r.recommendation}`
  ).join('\n\n');

  return [
    `# ${title}`,
    '',
    `**Scenario:** ${scenario}`,
    `**Agents:** ${nAgents} · **Steps:** ${nSteps} · **Generated:** ${date}`,
    '',
    '---',
    '',
    '## Final outcome metrics',
    '',
    '| Dimension | Start | Final | Change |',
    '|---|---|---|---|',
    `| Employment rate | ${empStart.toFixed(1)}% | ${empFinal.toFixed(1)}% | ${fmtDelta(empFinal - empStart, 1, '%')} |`,
    `| Welfare index | ${welStart.toFixed(3)} | ${welFinal.toFixed(3)} | ${fmtDelta(welFinal - welStart, 3)} |`,
    `| Infrastructure | ${infStart.toFixed(1)} | ${infFinal.toFixed(1)} | ${fmtDelta(infFinal - infStart, 1)} |`,
    `| Environment | ${envStart.toFixed(1)} | ${envFinal.toFixed(1)} | ${fmtDelta(envFinal - envStart, 1)} |`,
    '',
    '---',
    '',
    '## Overall assessment',
    '',
    consequence.overall || '',
    '',
    '---',
    '',
    '## Risk findings',
    '',
    riskBlocks,
    '',
    '---',
    '',
    '*Generated by CivicTwin · MESA agent-based model · Gemini 2.5 Flash · Currency: ₹ (Indian Rupees)*',
  ].join('\n');
}

/**
 * buildPDF — pure function: props → jsPDF doc.
 * Caller does doc.save(...).
 */
export function buildPDF({ scenario, nAgents, nSteps, meanByStep, consequence, scenarioLabel }) {
  const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const ML   = 20;   // left margin
  const MR   = 190;  // right margin (210 - 20)
  const TW   = 170;  // text width
  const date = new Date().toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
  });

  // jsPDF's built-in helvetica cannot render ₹ (renders as blank/box).
  // pdfSafe() replaces ₹ with Rs. in ALL strings before they hit jsPDF.
  const pdfSafe = (str) => (str || '').replace(/₹/g, 'Rs.');

  const {
    empStart, empFinal, welStart, welFinal,
    infStart, infFinal, envStart, envFinal,
  } = extractMetrics(meanByStep);

  let y = 20;

  // ── 1. Header ────────────────────────────────────────────────────────────
  const titleText = scenarioLabel
    ? `CivicTwin Policy Impact Report — ${scenarioLabel}`
    : 'CivicTwin Policy Impact Report';

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(30, 49, 80);
  doc.text(titleText, ML, y);
  y += 8;

  // Scenario (italic, wrapped) — pdfSafe strips ₹ → Rs.
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  const scenLines = doc.splitTextToSize(`Scenario: ${pdfSafe(scenario)}`, TW);
  doc.text(scenLines, ML, y);
  y += scenLines.length * 5 + 2;

  // Meta line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(140, 140, 140);
  doc.text(`Agents: ${nAgents} · Steps: ${nSteps} · Generated: ${date}`, ML, y);
  y += 5;

  // Rule
  doc.setDrawColor(220, 220, 220);
  doc.line(ML, y, MR, y);
  y += 7;

  // ── 2. Metrics table (manual, no autotable dependency) ───────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 49, 80);
  doc.text('Final Outcome Metrics', ML, y);
  y += 6;

  const cols   = [70, 28, 28, 28]; // column widths: dim | start | final | change
  const headers = ['Dimension', 'Start', 'Final', 'Change'];
  const rows = [
    ['Employment rate',
     `${empStart.toFixed(1)}%`, `${empFinal.toFixed(1)}%`,
     empFinal - empStart],
    ['Welfare index',
     welStart.toFixed(3), welFinal.toFixed(3),
     welFinal - welStart],
    ['Infrastructure',
     infStart.toFixed(1), infFinal.toFixed(1),
     infFinal - infStart],
    ['Environment',
     envStart.toFixed(1), envFinal.toFixed(1),
     envFinal - envStart],
  ];
  const ROW_H = 7;

  // Header row background
  doc.setFillColor(230, 235, 245);
  doc.rect(ML, y, cols[0] + cols[1] + cols[2] + cols[3], ROW_H, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 49, 80);
  let cx = ML + 2;
  headers.forEach((h, i) => { doc.text(h, cx, y + 5); cx += cols[i]; });
  y += ROW_H;

  // Data rows
  rows.forEach((row, ri) => {
    const bg = ri % 2 === 0 ? [255, 255, 255] : [248, 248, 248];
    doc.setFillColor(...bg);
    doc.rect(ML, y, cols[0] + cols[1] + cols[2] + cols[3], ROW_H, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(50, 50, 50);

    const delta = row[3];
    const deltaStr = (delta >= 0 ? '+' : '') + delta.toFixed(
      row[0] === 'Welfare index' ? 3 : 1
    ) + (row[0] === 'Employment rate' ? '%' : '');

    const cells = [row[0], row[1], row[2], deltaStr];
    cx = ML + 2;
    cells.forEach((cell, ci) => {
      if (ci === 3) {
        // Change column: green positive, red negative
        doc.setTextColor(delta >= 0 ? 29 : 226, delta >= 0 ? 158 : 75, delta >= 0 ? 117 : 74);
      } else {
        doc.setTextColor(50, 50, 50);
      }
      doc.text(String(cell), cx, y + 5);
      cx += cols[ci];
    });
    y += ROW_H;
  });

  // Table bottom border
  doc.setDrawColor(220, 220, 220);
  doc.line(ML, y, MR, y);
  y += 8;

  // ── 3. Overall assessment ────────────────────────────────────────────────
  // Check page overflow
  if (y > 240) { doc.addPage(); y = 20; }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 49, 80);
  doc.text('Overall Assessment', ML, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  const overallLines = doc.splitTextToSize(pdfSafe(consequence.overall || ''), TW);
  doc.text(overallLines, ML, y);
  y += overallLines.length * 5 + 8;

  // ── 4. Risk findings ─────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 49, 80);
  doc.text('Risk Findings', ML, y);
  y += 7;

  const risks = DIM_ORDER.map(
    dim => consequence.risks?.find(r => r.dimension === dim)
  ).filter(Boolean);

  risks.forEach((risk, ri) => {
    // Page overflow check
    if (y > 255) { doc.addPage(); y = 20; }

    const sev = SEV_COLORS[risk.severity] || SEV_COLORS.low;
    const hexToRgb = (hex) => {
      const r = parseInt(hex.slice(1, 3), 16);
      const g = parseInt(hex.slice(3, 5), 16);
      const b = parseInt(hex.slice(5, 7), 16);
      return [r, g, b];
    };

    // Severity badge (colored rect)
    const [br, bg, bb] = hexToRgb(sev.bg);
    const [tr, tg, tb] = hexToRgb(sev.text);
    doc.setFillColor(br, bg, bb);
    doc.roundedRect(ML, y, 28, 5.5, 1.5, 1.5, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(tr, tg, tb);
    doc.text(risk.severity.toUpperCase(), ML + 2, y + 4);

    // Dimension heading
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(30, 49, 80);
    doc.text(`${risk.dimension}`, ML + 32, y + 4);
    y += 8;

    // Finding — pdfSafe strips ₹ → Rs.
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const findingLines = doc.splitTextToSize(pdfSafe(risk.finding || ''), TW);
    doc.text(findingLines, ML, y);
    y += findingLines.length * 4.5 + 2;

    // Recommendation — pdfSafe strips ₹ → Rs.
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    const recLines = doc.splitTextToSize(`Recommendation: ${pdfSafe(risk.recommendation || '')}`, TW);
    doc.text(recLines, ML, y);
    y += recLines.length * 4.5;

    // Separator between risks (not after last)
    if (ri < risks.length - 1) {
      y += 3;
      doc.setDrawColor(230, 230, 230);
      doc.line(ML, y, MR, y);
      y += 5;
    }
  });

  // ── 5. Footer ─────────────────────────────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      'Generated by CivicTwin \u00B7 MESA agent-based model \u00B7 Gemini 2.5 Flash \u00B7 Currency: Rs. (INR)',
      105, 285, { align: 'center' }
    );
  }

  return doc;
}

// ── Component ────────────────────────────────────────────────────────────────

/**
 * ReportExporter
 * Renders null while data is loading; shows toolbar when both
 * meanByStep and consequence are non-null.
 */
const ReportExporter = ({
  scenario,
  nAgents,
  nSteps,
  meanByStep,
  consequence,
  scenarioLabel,
}) => {
  const [copyLabel, setCopyLabel] = useState('Copy markdown');

  // V5: render nothing until both props are present
  if (!meanByStep || !consequence) return null;

  // ── Handlers ──────────────────────────────────────────────────────────────
  const handleCopyMarkdown = () => {
    const md = buildMarkdown({ scenario, nAgents, nSteps, meanByStep, consequence, scenarioLabel });
    navigator.clipboard.writeText(md).then(() => {
      setCopyLabel('Copied!');
      setTimeout(() => setCopyLabel('Copy markdown'), 2000);
    }).catch(() => {
      // Fallback for browsers without clipboard API
      const ta = document.createElement('textarea');
      ta.value = md;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopyLabel('Copied!');
      setTimeout(() => setCopyLabel('Copy markdown'), 2000);
    });
  };

  const handleDownloadPDF = () => {
    const doc = buildPDF({ scenario, nAgents, nSteps, meanByStep, consequence, scenarioLabel });
    const safeScenario = (scenario || 'report')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .slice(0, 40);
    const dateStr = new Date().toISOString().slice(0, 10);
    doc.save(`civictwin-${safeScenario}-${dateStr}.pdf`);
  };

  // ── Typography tokens (matches ConsequencePanel) ──────────────────────────
  const label = scenarioLabel || 'Simulation report ready';

  return (
    <div style={{
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'space-between',
      flexWrap:       'wrap',
      gap:            '0.75rem',
      marginTop:      '1rem',
      padding:        '0.75rem 1rem',
      background:     'var(--color-background-secondary, #f9fafb)',
      border:         '1px solid var(--color-border-tertiary, #e5e7eb)',
      borderRadius:   10,
    }}>
      {/* Label */}
      <span style={{
        fontSize:   13,
        fontWeight: 500,
        color:      'var(--color-text-secondary, #6b7280)',
        display:    'flex',
        alignItems: 'center',
        gap:        '0.4rem',
      }}>
        <span style={{ fontSize: 15 }}>📄</span>
        {label}
      </span>

      {/* Action buttons */}
      <div style={{ display: 'flex', gap: '0.5rem', flexShrink: 0 }}>
        <button
          id={`copy-md-${(scenarioLabel || 'single').replace(/\s+/g, '-').toLowerCase()}`}
          onClick={handleCopyMarkdown}
          style={{
            padding:      '0.4rem 0.9rem',
            fontSize:     13,
            fontWeight:   500,
            border:       '1px solid var(--color-border-tertiary, #e5e7eb)',
            borderRadius: 8,
            background:   copyLabel === 'Copied!' ? '#E1F5EE' : 'white',
            color:        copyLabel === 'Copied!' ? '#085041' : 'var(--color-text-primary, #111827)',
            cursor:       'pointer',
            transition:   'background 0.2s, color 0.2s',
          }}
        >
          {copyLabel === 'Copied!' ? '✓ Copied!' : '📋 Copy markdown'}
        </button>

        <button
          id={`download-pdf-${(scenarioLabel || 'single').replace(/\s+/g, '-').toLowerCase()}`}
          onClick={handleDownloadPDF}
          style={{
            padding:      '0.4rem 0.9rem',
            fontSize:     13,
            fontWeight:   500,
            border:       'none',
            borderRadius: 8,
            background:   'var(--primary-color, #1E3150)',
            color:        'white',
            cursor:       'pointer',
          }}
        >
          ⬇ Download PDF
        </button>
      </div>
    </div>
  );
};

export default ReportExporter;
